### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by iteles** [cul-2016/site#1]
As a Product Owner, I'd like to have a homepage which includes information on my product and a couple of places with buttons (like a 'Start the tour' and/or 'Start a free trial') so that anyone who lands on the front page has the information they need.

## Acceptance Criteria
+ [x] All text on the homepage is editable via the CMS (open question on whether the navigation and footer also need to be editable)
+ [x] 'Start the Tour' button and 'Start a free trial' button text is also editable if possible
+ [x] Homepage matches the designs

**Comment by Cleop** [comment]
So far the navigation is editable

Not editable: the 'Quodl' left part of the nav including the logo image
