### ISSUE TITLE
Pricing page

### ISSUE THREAD

**Issue by iteles** [cul-2016/site#10]
As a site owner
I would like to have a pricing page with some information around the benefits of Quodl and the various pricing tiers
So that interested visitors can contact us if they're interested in using Quodl.

_Note:_ For now, this will be just a link to the contact form or a mailto link, no payment processing will be integrated at this stage

## Acceptance Criteria
~+ [ ] There is a section on the benefits of Quodl (currently referred to in our designs as 'Student Retention'~
+ [x] There is a section with the various (3 for now) tiers of pricing including explanatory text (should follow the [familiar user pattern for this](https://www.google.co.uk/search?q=images+pricing+levels&source=lnms&tbm=isch&sa=X&ved=0ahUKEwj6_8qnge7YAhWSbVAKHWy-CIEQ_AUICigB&biw=1600&bih=873#imgrc=A2kvTWN0wI-O3M:))
+ [x] An FAQ section is included
+ [x] There is a link which allows visitors to email/communicate with the site owner

**Comment by harrygfox** [comment]
To clarify, the benefits of Quodl are specifically aimed at those making the purchasing decision - the members of the university who determine which tools and services go into teaching. This is not benefits for lecturers directly nor to students directly but focuses on the fact that there will be higher "student retention" ie fewer students drop out, meaning more money for the university.

**Comment by Cleop** [comment]
For the time being the FAQs section was created instead of the benefits of quodl section - would you like to separate that checkbox out as a separate issue or keep it open for now?

**Comment by iteles** [comment]
@Cleop Updated the issue above! This is ready to be closed 👍
