### ISSUE TITLE
Contact form

### ISSUE THREAD

**Issue by iteles** [cul-2016/site#12]
As a site owner
I would like to have a page with a contact form which allows visitors to select from a drop-down list of subjects
So that both our visitors have the ability to contact us and also so that we know how best to direct their enquiry.

## Acceptance
+ [x] This is an individual page with a title, possibly an introductory sentence and then a contact form
~+ [ ] The contact form has a drop-down list of topics which are editable in the CMS (editability requirements TBC)~
+ [ ] Submitting the contact form sends an email to a particular support email #42 
  + [ ] This email contains all of the information submitted in the form
+ [x] TBC mandatory fields - once we know what these are (email will be one for example), ensure that if these fields are not filled in, a friendly but visible warning message appears to let the user know the form hasn't been submitted and certain information is required

**Comment by Cleop** [comment]
@iteles - when you say:
> Submitting the contact form sends an email to a particular support email

Do you mean one particular support email (for all of the submitted forms) or do you mean a particular email according to the type of form submitted ie. sales requests go to one email address and technical problems go to another one?

**Comment by iteles** [comment]
Good question @Cleop, I'll run these by our PO tomorrow

**Comment by Cleop** [comment]
Starting off with [apostrophe-pieces-submit-widgets](https://www.npmjs.com/package/apostrophe-pieces-submit-widgets) package to test the ability to use a contact form, will explore whether it can do everything we need in terms of performance.

**Comment by Cleop** [comment]
@iteles - can the dropdown list checkbox be taken out of the list of requirements as it wasn't in the designs?

**Comment by iteles** [comment]
Closing this issue as email alerts are now captured in #42
