### ISSUE TITLE
Quick Start

### ISSUE THREAD

**Issue by shouston3** [cul-2016/site#14]
As a developer looking to run the `site` locally, I would like to see a section in the readme explaining this could be done

**Comment by Cleop** [comment]
To add to the readme:
- Install mongo
- clone repo
- `npm i`
- `node app.js apostrophe-users:add admin admin` and set a password for your admin
- Then go to `http://0.0.0.0:3000/login` and enter username admin and your password

**Comment by shouston3** [comment]
Looks good @Cleop
