### ISSUE TITLE
Spike: Investigate CMS suitability

### ISSUE THREAD

**Issue by Cleop** [cul-2016/site#2]
Following my [research into CMS options](https://github.com/dwyl/adoro/issues/3#issuecomment-358913000) we have narrowed down our choices to Ghost and Apostrophe. Now in order to understand which is most suitable we are going to do a short spike into each of these to learn more. I will be looking at Ghost whilst @finnhodgkin will be looking at Apostrophe. We will record our findings in here and choose a CMS by the end of the day.

**Comment by finnhodgkin** [comment]
## First impressions of [Apostrophe](http://apostrophecms.org/) 

It's _really_ easy to get set up and running!

![apostrophe](https://user-images.githubusercontent.com/22300773/35225016-0617cffa-ff7f-11e7-8f5e-1a02cca3fd53.gif)

There's a great beginner's guide that takes you through the installation and templating 
process, and I can already see exactly how you would build fairly complex layouts with text editing integration. :+1:

The CMS side of things is 'widget' based - signed in admins just click directly on the existing page content to make edits or add new sections (widgets). This means the page isn't limited to just a title/content like some blog sites, and the text editing is 'rich text' so there's no markdown/html on the client-side. Image selection/upload is also included out of the box.

### The docs

On first impression the Apostrophe documentation seems to be thorough but not terribly well organised. There's just a giant list of alphabetised module names so unless you know exactly what you're looking for it's hard to know where to look.  

### CSS

It comes bundled with Less for css but it was v. easy to swap out it for tachyons (you can add `<style>` and `<script>` tags like any other static site).

### JS

Lodash / jQuery are bundled by default and there doesn't seem to be an easy way to remove
them. Bundling doesn't seem to be provided so no access to brunch/webpack, and no npm/require on the front-end.

### Links

Example demo: http://demo.apostrophecms.org/
Beginner guide: http://apostrophecms.org/docs/tutorials/getting-started/index.html
Docs: http://apostrophecms.org/docs/

## Issues so far:

* Intro tutorial differs slightly from the current version. The configuration file
  for pages is contained in `/lib/modules/apostrophe-templates/index.js` rather
  than `/app.js`. The change is documented in comments within `/app.js` but it may be a sign of annoying documentation issues in the future.

* Can't use nodemon out of the box and there's no inbuilt hot reloader. I haven't 
Googled this and I guess it's not the end of the world, just a little annoying when 
working on css.

**Comment by Cleop** [comment]
## Reflections on [Ghost](https://ghost.org/)

### Setup on a Mac

- Tells you to create users in the instructions before you've even set up your server
- Instructions are focused on Ubuntu

Ie. `brew install nginx` not `sudo apt-get...`

- You need:
  - [ ] NGINX (min 1.9.5)
  - [ ] Node (v6) - make sure you have a supported version of Node, check the docs
  - [ ] MySQL (`brew install mysql` NOT MySQL-server, doesn't exist on brew) 

Ensure that MySQL is installed with a password specified (as per the Ghost documentation):
![image](https://user-images.githubusercontent.com/16775804/35219268-db0a2cb4-ff69-11e7-90c6-b39e03fa75cb.png)

**Problems I encountered/ instructions I chose not to follow:**
- Error message on MySQL
- MySQL is not MySQL-server
- ufw allow 'Nginx Full' - have not run with sudo yet so did not work
- Haven't installed Node via NodeSource as they specified
- Says to install yarn, I've not

You must install ghost-cli globally, everything else I didn't install globally even when it tells you to: `npm i -g ghost-cli`

Do `sudo mkdir -p /var/www/ghost` or `sudo mkdir -p /var/www/{folder}` - **must** use sudo

Do `cd /var/www/ghost`, then `sudo ghost install`

![image](https://user-images.githubusercontent.com/16775804/35225251-b4a460ec-ff7f-11e7-8720-2b6ac87b8ba2.png)

-------------------------
Based on the journey above, now going to pursue the local option: `ghost install local`. Make sure your repo is totally empty before doing this.

![image](https://user-images.githubusercontent.com/16775804/35225413-2f21e574-ff80-11e7-8f15-06753aed95c9.png)

This runs like the production example but skipping the following sections:
<img src="https://user-images.githubusercontent.com/16775804/35225654-ce960a2c-ff80-11e7-9863-0d0a9076f29b.png" width=350px />

**Comment by Cleop** [comment]
We are going to proceed with Apostrophe because it is more of an all-round CMS (rather than Ghost being publishing centric), it is compliant with both Ubuntu and OS X and has good documentation and options for module expansion.
