### ISSUE TITLE
'Log in' button to appear next to burger menu on mobile

### ISSUE THREAD

**Issue by iteles** [cul-2016/site#38]
As logging in is the key things that mobile users (probably students in lecturers) will want to do, we would like to have the 'Log in' orange CTA button _next_ to the burger menu on mobile so that users see it immediately when using the page on mobile.

- [x] Move log in button on mobile

**Comment by Cleop** [comment]
This has now been added:
![image](https://user-images.githubusercontent.com/16775804/35810082-72de057e-0a82-11e8-8787-14c4d063a93c.png)
