### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by stianr** [cul-2016/site#49]
As noted in email to @finnhodgkin, the quodl site doesn't seem to be working. If I go to http://quodl-site.herokuapp.com I get:

> Application error
> An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.

Recent logs from heroku below:

> 2018-04-30T08:07:38.546317+00:00 app[web.1]: npm ERR! quodl-site@2.0.0 start: `node app.js`
> 2018-04-30T08:07:38.546546+00:00 app[web.1]: npm ERR! Exit status 1
> 2018-04-30T08:07:38.550472+00:00 app[web.1]: npm ERR! 
> 2018-04-30T08:07:38.550712+00:00 app[web.1]: npm ERR! Failed at the quodl-site@2.0.0 start script.
> 2018-04-30T08:07:38.550929+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 2018-04-30T08:07:38.657572+00:00 app[web.1]: 
> 2018-04-30T08:07:38.657991+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
> 2018-04-30T08:07:38.658396+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2018-04-30T08_07_38_553Z-debug.log
> 2018-04-30T10:13:47.791476+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=quodl-site.herokuapp.com request_id=7e32334f-b13b-499e-8979-d73770ce2c4d fwd="138.40.68.132" dyno= connect= service= status=503 bytes= protocol=http
> 2018-04-30T10:13:48.366777+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=quodl-site.herokuapp.com request_id=6b1430f9-bee4-402e-a5f7-ff886abb33c4 fwd="138.40.68.132" dyno= connect= service= status=503 bytes= protocol=http

I noticed this as I was updating the DNS settings to associate the site with the right URL, but I don't think that was a causal factor, as (a) I've reset the DNS settings to their previous values, (b) I saw something like this a few days ago but assumed it was temporary, (c) what I was doing is peripheral to the site functionality so I can't see how it could cause a crash...

This is the only thing preventing us from making the site live, so it would be good to get it fixed as soon as possible, assuming it's straightforward.

**Comment by shouston3** [comment]
@stianr http://quodl-site.herokuapp.com is working for me

It might be down just for you (See here to check: https://downforeveryoneorjustme.com/quodl-site.herokuapp.com)

**Comment by shouston3** [comment]
@iteles @finnhodgkin could you confirm

**Comment by iteles** [comment]
@stianr Finn redeployed this morning and that seemed to do the trick - may have been a build error on deployment but we should keep an eye on it!

**Comment by stianr** [comment]
Definitely - will reopen this if it happens again.
