### ISSUE TITLE
Articles / Blog

### ISSUE THREAD

**Issue by iteles** [cul-2016/site#8]
As a site owner,
I would like to have an area where I can write blogs and where visitors to my site can read the articles most relevant to them
So that they are drawn back to the website because they know the content will be targeted.

## Acceptance Criteria
+ [x] There must be a way to create new blog posts through the CMS
+ [x] Each blog post should be able to be tagged with a series of tags (TBD whether these are pre-defined or fluid - with the exception of 'All', 'For lecturers' and 'For students')
+ [x] The blog page must display three categories of blog posts which I am allowed to filter on: 'All', 'For lecturers' and 'For students'
  + [x] When I click on any one of these categories, I am taken to a filtered view of this page by that category
+ [x] The default display page should be 'All', showing all of the blog posts available
+ [x] This page must display x (TBD) number of articles with a 'See More' button to view the rest
+ [x] Each blog post must be displayed in a box with information TBD (@Cleop @finnhodgkin for now it's worth looking into displaying the title and the opening few sentences but also understanding how this would work if an image opened the post)
+ [x] Clicking anywhere in the box displaying the title of the blog post will take the visitor to the post itself

**Comment by Cleop** [comment]
Note: the blog posts are currently displaying in order of date published with the most recent first.
