### ISSUE TITLE
Individual blog post page

### ISSUE THREAD

**Issue by iteles** [cul-2016/site#9]
As a site owner
I would like to have each blog post displayed as an individual page
So that visitors can access the full text quickly and easily or share links to individual blog posts without any difficulty.

## Acceptance Criteria
+ [x] Page will include the blog post title, text and all relevant images

**TBD:**
+ [x] Page will include author name
+ [ ] Page will allow commenting from visitors

**Comment by Cleop** [comment]
Need to look into options for blog cards at the bottom of the blog article page:
Currently it uploads the whole article and you can filter by tag but I'm not sure how this would be reproduced from page to page ie. if you have to do it manually. Also at the moment it might recommend the blog that you are currently on which is not ideal either.
![image](https://user-images.githubusercontent.com/16775804/35347270-8adc80ec-012c-11e8-810b-46d759697a39.png)

**Comment by finnhodgkin** [comment]
https://www.facebook.com/sharer/sharer.php?u=example.org

https://www.linkedin.com/cws/share?url=hello.com

http://twitter.com/share?text=text%20goes%20here&url=http://quodl.co.uk&hashtags=hashtag1,hashtag2,hashtag3

**Comment by Cleop** [comment]
@iteles - the designs did not feature anything indicating the tag/category of the blog, the designs also did not include commenting

Would you like to keep this issue open for now?

**Comment by iteles** [comment]
Let's close this issue for now and we can open a new issue on comments if it becomes a requirement.
